# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Nppang_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Nppang_iOS
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'FirebaseFirestore'
  pod 'GoogleSignIn','5.0.2'
  pod 'DropDown'

end
